# General settings for the TuTienTranPhap plugin

# CONFIGURATION VERSION (DO NOT CHANGE)
config-version: '${project.version}'

# Default language of the plugin. Supported: 'en' (English), 'vi' (Vietnamese)
language: 'en'

# Enable/Disable debug messages in the console (e.g., "Loaded formation...")
# Default: true
debug-logging: true

# How often to apply effects to players and mobs in the formation.
# Unit: ticks (20 ticks = 1 second)
# A lower value makes the effects smoother but uses more resources.
# Default: 20 (apply effects every second)
effect-check-interval-ticks: 20

blueprint:
  # If true, players will need the required blocks in their inventory to build a formation.
  # The blueprint item itself will still be consumed.
  # Default: true
  require-materials: true

  # List of blocks that can be replaced when a player uses a blueprint.
  # Use official Material names from Bukkit: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html
  replaceable-blocks:
    - "AIR"
    - "GRASS"
    - "TALL_GRASS"
    - "FERN"
    - "LARGE_FERN"
    - "DEAD_BUSH"
    - "VINE"
    - "POPPY"
    - "DANDELION"
    - "BLUE_ORCHID"
    - "ALLIUM"
    - "AZURE_BLUET"
    - "RED_TULIP"
    - "ORANGE_TULIP"
    - "WHITE_TULIP"
    - "PINK_TULIP"
    - "OXEYE_DAISY"
    - "CORNFLOWER"
    - "LILY_OF_THE_VALLEY"
    - "WITHER_ROSE"
    - "SUNFLOWER"
    - "LILAC"
    - "ROSE_BUSH"
    - "PEONY"
    - "BROWN_MUSHROOM"
    - "RED_MUSHROOM"
    - "SNOW"
    - "GRASS_BLOCK"
    - "DIRT"
    - "PODZOL"
    - "COARSE_DIRT"
    - "MYCELIUM"
    - "DIRT_PATH"