# src/main/resources/plugin.yml
name: TuTienTranPhap
version: ${project.version}
main: com.alilshady.tutientranphap.TuTienTranPhap
api-version: 1.20
author: AlilShady
description: Một hệ thống Trận Pháp (Tu tiên) có khả năng tùy chỉnh cao.
commands:
  tutientranphap:
    description: Lệnh chính của plugin TuTienTranPhap.
    usage: /<command> [reload|give|test]
    aliases: [tranphap, tttp]
permissions:
  tutientranphap.reload:
    description: Cho phép người dùng tải lại cấu hình của plugin.
    default: op
  tutientranphap.give:
    description: Cho phép người dùng lấy Trận Đồ.
    default: op
  tutientranphap.test:
    description: Cho phép người dùng kích hoạt thử nghiệm trận pháp.
    default: op