# Cài đặt chung cho plugin TuTienTranPhap

# PHIÊN BẢN CẤU HÌNH (KHÔNG THAY ĐỔI)
config-version: '1.0.0'

# Ngôn ngữ mặc định của plugin. Hỗ trợ: 'en' (English), 'vi' (Tiếng Việt)
language: 'en'

# Bật/Tắt các tin nhắn debug trong console (ví dụ: "Loaded formation...")
# Mặc định: true
debug-logging: true

# Tần suất áp dụng hiệu ứng cho người chơi và quái vật trong trận pháp.
# Đơn vị: tick (20 ticks = 1 giây)
# Giá trị càng thấp, hiệu ứng càng mượt nhưng càng tốn tài nguyên.
# Mặc định: 20 (áp dụng hiệu ứng mỗi giây)
effect-check-interval-ticks: 20