# src/main/resources/plugin.yml
name: EssenceArrays
version: 1.1.1
main: com.alilshady.tutientranphap.EssenceArrays
api-version: 1.20
author: AlilShady
description: A highly customizable Cultivation Formation system.
commands:
  essencearrays:
    description: Main command for the EssenceArrays plugin.
    usage: /<command> [reload|give|test]
    aliases: [ess]
permissions:
  essencearrays.reload:
    description: Allows the user to reload the plugin's configuration.
    default: op
  essencearrays.give:
    description: Allows the user to get a Formation Blueprint.
    default: op
  essencearrays.test:
    description: Allows the user to test activate a formation.
    default: op