# src/main/resources/plugin.yml
name: TuTienTranPhap
version: 1.0.0
main: com.alilshady.tutientranphap.TuTienTranPhap
api-version: 1.20
author: AlilShady
description: A highly customizable Cultivation Formation system.
commands:
  tutientranphap:
    description: Main command for the TuTienTranPhap plugin.
    usage: /<command> [reload|give|test]
    aliases: [tranphap, tttp]
permissions:
  tutientranphap.reload:
    description: Allows the user to reload the plugin's configuration.
    default: op
  tutientranphap.give:
    description: Allows the user to get a Formation Blueprint.
    default: op
  tutientranphap.test:
    description: Allows the user to test activate a formation.
    default: op